import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import React, { useState } from "react";
import {
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  UploadOutlined,
  UserOutlined,
  VideoCameraOutlined,
} from "@ant-design/icons";
import { Button, Layout, Menu, theme } from "antd";
import MenuAppBar from "../components/MenuAppBar/index";
import Sidebar from "../components/Sidebar/index";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Teach Together",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ backgroundColor: "#D9D9D9" }}>
        <Layout style={{ minHeight: "100vh" }}>
            <Sidebar />

          <Layout>
              <MenuAppBar />

              <div style={{ padding: 24, background: "#fff", minHeight: 360 }}>
                {children}
              </div>
          </Layout>
        </Layout>
      </body>
    </html>
  );
}
